### PR TITLE
Mark FreeBSD as tested and add pkg install (#214)

### LINKED ISSUE #214: Test on FreeBSD

### PR DESCRIPTION
**Pull request by fujiapple852**
Closes #214

### CODE REVIEW

**Comment by fujiapple852** [comment]
@ehaupt I was just waiting for the package to be visible in https://repology.org/project/trippy/versions (as that is what the `README.md` badge links to) but it doesn't seem to be there yet.  From the charts in https://repology.org/repository/freebsd it looks like there may be some delay in updates coming through.  

Maybe I'll just link the badge directly to `https://www.freshports.org/net/trippy/` for now.

**Comment by ehaupt** [comment]
I figured. I have noticed that repology doesn't update FreeBSD versions in the last few days and have messaged @AMDmi3 about it.

**Comment by ehaupt** [comment]
@AMDmi3 Thanks for the update.

**Comment by fujiapple852** [comment]
Looks to be fixed so I've updated `README.md` to point at the `repology.org` badge:

```
[![FreeBSD port](https://repology.org/badge/version-for-repo/freebsd/trippy.svg)](https://www.freshports.org/net/trippy/)
```

Thanks to you both.

**Comment by ehaupt** [comment]
> Looks to be fixed so I've updated `README.md` to point at the `repology.org` badge:
> 
> ```
> [FreeBSD port](https://www.freshports.org/net/trippy/)
> ```
> 
> Thanks to you both.

Thank you for the update. It sure looks good now:
[Packaging status](https://repology.org/project/trippy/versions)

**Pull request merged**
