### PR TITLE
Release 0.7.0

### PR DESCRIPTION
**Pull request by fujiapple852**

### CODE REVIEW

**Comment by fujiapple852** [comment]
@0323pin I have been unable to revive my AWS based `netbsd` setup to test the latest release of trippy, would you be so kind as to give it a try?

**Comment by 0323pin** [comment]
@fujiapple852 Yes, of course. Kick-starting a build right away. Get back to you soon.

**Comment by 0323pin** [comment]
@fujiapple852 All good :)

```
~ > uname -v
NetBSD 10.99.2 (GENERIC) #0: Fri Mar 17 17:16:06 UTC 2023  mkrepro@mkrepro.NetBSD.org:/usr/src/sys/arch/amd64/compile/GENERIC
~ > pkg_info | grep rust
rust-1.68.0         Safe, concurrent, practical language
~ > trip -V
trippy 0.7.0
```

2023-03-25-162858_1366x768_scrot

**Comment by 0323pin** [comment]
@fujiapple852 Just one thing. We are on a commit freeze ahead of the stable-release for 2023Q1, I will merge the update as soon as the freeze is over. Should end on Monday.

**Pull request merged**
